---
- hosts: '{{ host }}'
  gather_facts: no
  remote_user: xiyoucs

  tasks:
    win_user:
      name: '{{ user }}'
      password: '{{ password }}'
      groups: Administrators,Remote Desktop Users
      update_password: always
      user_cannot_change_password: yes
